services:
  db:
    image: postgres:15-alpine
    container_name: community_flow_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: community_flow
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - community_net

networks:
  community_net:


volumes:
  postgres_data:
